# This is a template _quarto.yml file.
# The rest of the content for this file 
# is injected via _theme/build.sh and 
# _theme/build-quarto-yml.R

project:
  type: book

book:
  title: "Engineering: What are we doing?"
  author: "Matthew Kuperus Heun"
  date: "2026-05-29"
  chapters:
    - index.qmd
    - introduction.qmd
    - creation.qmd
    - problems.qmd
    - redemption.qmd
    - conclusion.qmd
    - afterword.qmd

#### Additional content is generated here ####

  # favicon: __FAVICON__
  # navbar: __NAVBAR__
  # page-footer: __PAGE-FOOTER__

# format: __FORMAT__
# execute: __EXECUTE__
