# Introduction

Thank you for that kind introduction, Jeremy. 
I’m humbled and honored to have been asked to speak today.
I hope that many of you, like me, 
have been blessed by the previous 
keynotes, sessions, events, and devotions.
I’m grateful to the many presenters who have made me
think differently, 
challenged assumptions, and 
enriched my soul in the last couple days. 
I pray that I can do the same in the upcoming 50 minutes.

Like previous speakers, I want to tell a story. 
But not my biography. 
As I’m nearing the end of my teaching career, 
I, rather, want to share my hard-won understanding 
of engineering and the work of engineers 
through the eyes of faith in Jesus Christ. 
Thus, my title, 
"Engineering: What are we doing?"
Perhaps some things will sound familiar. 
Maybe other things will be challenging. 
Hopefully at least one thing will be helpful to each of you.

Along the way, I’ll tell a few anecdotes, and
I’ll ask you to participate in short bursts, 
which is why you’re hopefully sitting in a row assigned to your discipline. 
But if not, that’s OK.

Now, I'm no preacher or theologian, 
and this isn't a sermon, 
but my talk has three parts that 
I won't name but should be discernable. 
I have a small Lego gift for the first five people 

-	who I don’t know, 
-	who introduce themselves, and 
-	who correctly identify all three parts. 

Come find me later.

OK! If you’re ready, I’m ready. Let’s get started.
